const input = "a1b2cc";

/**
 * Returns all permutations of strings that can be generated by
 * converting each letter to both lowercase and uppercase.
 * Digits remain unchanged.
 * 
 * Algorithm: Iteratively build permutations by processing each character.
 * For letters, each existing permutation branches into two (lowercase/uppercase).
 * For digits, simply append to all existing permutations.
 * 
 * @param {string} s - Input string containing letters and digits
 * @returns {string[]} Array of all letter case permutations
 */
const letterCasePermutations = function(s) {
    // Start with empty string to build permutations character by character
    let result = [""];

    // Process each character in the input string
    for (let char of s) {
        // Temporary array to store new permutations for this iteration
        let temp = [];

        // Check if character is a letter (not a digit)
        if (/[a-zA-Z]/.test(char)) {

            // For letters: each existing permutation branches into two
            // (one with lowercase, one with uppercase)
            // Example: ["a1"] + "b" → ["a1b", "a1B"]
            for (let str of result) {
                temp.push(str + char.toLowerCase());
                temp.push(str + char.toUpperCase());
            }
        } else {
            // For digits: simply append to all existing permutations
            for (let str of result) {
                temp.push(str + char);
            }
        }

        // Update result with new permutations
        result = temp;
    }

    return result;
}

const answer = letterCasePermutations(input);
console.log("answer :", answer);
